public let AEROSPACE_WINDOW_ID = "SIMPLEWM_WINDOW_ID"
public let AEROSPACE_WORKSPACE = "SIMPLEWM_WORKSPACE"
public let SIMPLEWM_FOCUSED_WORKSPACE = "SIMPLEWM_FOCUSED_WORKSPACE"
public let SIMPLEWM_PREV_WORKSPACE = "SIMPLEWM_PREV_WORKSPACE"
