public let FRAME_WINDOW_ID = "FRAME_WINDOW_ID"
public let FRAME_WORKSPACE = "FRAME_WORKSPACE"
public let FRAME_FOCUSED_WORKSPACE = "FRAME_FOCUSED_WORKSPACE"
public let FRAME_PREV_WORKSPACE = "FRAME_PREV_WORKSPACE"
