#!/bin/bash
cd "$(dirname "$0")/../.."
source ./script/setup.sh
source ./script/identity.sh

build_version="" # mandatory
while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2;;
        *) echo "Unknown arg $1"; exit 1;;
    esac
done

if test -z "$build_version"; then echo "--build-version is mandatory" > /dev/stderr; exit 1; fi
if ! [[ "$build_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-.][0-9A-Za-z.]+)?$ ]]; then
    echo "Invalid --build-version '$build_version'. Expected semantic-style version." > /dev/stderr
    exit 1
fi

zip_file=''
temp_zip_file=''
dist_zip_path="$FRAME_DIST_DIR/${FRAME_RELEASE_PREFIX}$build_version.zip"
release_zip_uri="${FRAME_REPO_URL}/releases/download/v$build_version/${FRAME_RELEASE_PREFIX}$build_version.zip"
if test -f "$dist_zip_path"; then
    zip_file=$dist_zip_path
else
    temp_zip_file="$(mktemp -t frame-cask-zip.XXXXXX)"
    trap '[[ -n "$temp_zip_file" ]] && rm -f "$temp_zip_file"' EXIT
    zip_file="$temp_zip_file"
    curl --fail --silent --show-error --location "$release_zip_uri" -o "$zip_file"
fi
sha=$(shasum -a 256 "$zip_file" | awk '{print $1}')

cask_version="'$build_version'"
version_template='#{version}'
zip_root_dir="${FRAME_RELEASE_PREFIX}${version_template}"
release_zip_uri="${FRAME_REPO_URL}/releases/download/v${version_template}/${FRAME_RELEASE_PREFIX}${version_template}.zip"

mkdir -p "$FRAME_DIST_DIR"
rm -f "$FRAME_DIST_DIR/${FRAME_CASK_STABLE}.rb"
cat > "$FRAME_DIST_DIR/${FRAME_CASK_STABLE}.rb" <<EOF
cask "$FRAME_CASK_STABLE" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version $cask_version
  sha256 "$sha"

  url "$release_zip_uri"
  name "$FRAME_PRODUCT_NAME"
  desc "$FRAME_TAGLINE"
  homepage "$FRAME_REPO_URL"

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/$zip_root_dir/bin/$FRAME_CLI_NAME"
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{appdir}/$FRAME_PRODUCT_NAME.app"
  end

  app "$zip_root_dir/$FRAME_PRODUCT_NAME.app"
  binary "$zip_root_dir/bin/$FRAME_CLI_NAME"
end
EOF
