#!/bin/bash
cd "$(dirname "$0")/../.."
source ./script/setup.sh
source ./script/identity.sh

zip_uri='' # mandatory
build_version="" # mandatory
while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2;;
        --zip-uri) zip_uri="$2"; shift 2;;
        *) echo "Unknown arg $1"; exit 1;;
    esac
done

if test -z "$zip_uri"; then echo "--zip-uri is mandatory" > /dev/stderr; exit 1; fi
if test -z "$build_version"; then echo "--build-version is mandatory" > /dev/stderr; exit 1; fi
if ! [[ "$build_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-.][0-9A-Za-z.]+)?$ ]]; then
    echo "Invalid --build-version '$build_version'. Expected semantic-style version." > /dev/stderr
    exit 1
fi

zip_file=''
temp_zip_file=''
if test -f "$zip_uri"; then
    zip_file=$zip_uri
    zip_uri="file://$(realpath "$zip_file")"
elif grep -Eq '^https?://' <<< "$zip_uri"; then
    temp_zip_file="$(mktemp -t frame-cask-zip.XXXXXX)"
    trap '[[ -n "$temp_zip_file" ]] && rm -f "$temp_zip_file"' EXIT
    zip_file="$temp_zip_file"
    curl --fail --silent --show-error --location "$zip_uri" -o "$zip_file"
else
    echo "$zip_uri doesn't exist" > /dev/stderr; exit 1
fi
sha=$(shasum -a 256 "$zip_file" | awk '{print $1}')

cask_version="'$build_version'"
zip_root_dir="${FRAME_RELEASE_PREFIX}$build_version"
zip_root_dir=$(sed "s/$build_version/#{version}/g" <<< "$zip_root_dir")
zip_uri=$(sed "s/$build_version/#{version}/g" <<< "$zip_uri")

mkdir -p "$FRAME_DIST_DIR"
rm -f "$FRAME_DIST_DIR/${FRAME_CASK_STABLE}.rb" || true
cat > "$FRAME_DIST_DIR/${FRAME_CASK_STABLE}.rb" <<EOF
cask "$FRAME_CASK_STABLE" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version $cask_version
  sha256 "$sha"

  url "$zip_uri"
  name "$FRAME_PRODUCT_NAME"
  desc "$FRAME_PRODUCT_NAME is an i3-like tiling window manager for macOS"
  homepage "$FRAME_REPO_URL"

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{staged_path}/$zip_root_dir/bin/$FRAME_CLI_NAME"
    system "xattr -d com.apple.quarantine #{appdir}/$FRAME_PRODUCT_NAME.app"
  end

  app "$zip_root_dir/$FRAME_PRODUCT_NAME.app"
  binary "$zip_root_dir/bin/$FRAME_CLI_NAME"
end
EOF
