#!/bin/bash
cd "$(dirname "$0")"
source ./script/setup.sh
source ./script/identity.sh

# Grammar is not expected to change very often, that's why it's not regenerated by default.
./generate.sh --ignore-xcodeproj --ignore-shell-parser
swift build "$@"

rm -rf .debug && mkdir .debug
cp -r ".build/debug/${FRAME_CLI_NAME}" .debug
cp -r ".build/debug/${FRAME_DEBUG_APP_BINARY}" .debug
