// FILE IS GENERATED FROM docs/aerospace-*.adoc files
// TO REGENERATE THE FILE RUN generate.sh

let subcommandDescriptions = [
    ["  balance-sizes", "Balance sizes of all windows in the current workspace"],
    ["  config", "Query AeroSpace config options"],
    ["  debug-windows", "Interactive command to record Accessibility API debug information to create bug reports"],
    ["  enable", "Temporarily disable window management"],
    ["  focus-back-and-forth", "Switch between the current and previously focused elements back and forth"],
    ["  focus-monitor", "Focus monitor by relative direction, by order, or by pattern"],
    ["  focus", "Set focus to a window."],
    ["  fullscreen", "Toggle the fullscreen mode for the focused window"],
    ["  layout", "Change layout of the focused window to the given layout"],
    ["  list-apps", "Print the list of running applications that appears in the Dock and may have a user interface"],
    ["  list-exec-env-vars", "List environment variables that exec-* commands and callbacks are run with"],
    ["  list-modes", "Print a list of modes currently specified in the configuration"],
    ["  list-monitors", "Print monitors that satisfy conditions"],
    ["  list-windows", "Print windows that satisfy conditions"],
    ["  list-workspaces", "Print workspaces that satisfy conditions"],
    ["  mode", "Activate the specified binding mode"],
    ["  move-mouse", "Move mouse to the requested position"],
    ["  move-node-to-monitor", "Move window to monitor targeted by relative direction, by order, or by pattern"],
    ["  move-node-to-workspace", "Move the focused window to the specified workspace"],
    ["  move-workspace-to-monitor", "Move workspace to monitor targeted by relative direction, by order, or by pattern."],
    ["  move", "Move the focused window in the given direction"],
    ["  reload-config", "Reload currently active config"],
    ["  resize", "Resize the focused window"],
    ["  summon-workspace", "Move the requested workspace to the focused monitor."],
    ["  swap", "Swaps the focused window with another window."],
    ["  trigger-binding", "Trigger AeroSpace binding as if it was pressed by user"],
    ["  workspace-back-and-forth", "Switch between the focused workspace and previously focused workspace back and forth"],
    ["  workspace", "Focus the specified workspace"],
]
