#!/bin/bash
cd "$(dirname "$0")/../.."
source ./script/setup.sh
source ./script/identity.sh

export XCODEGEN_FRAME_CODE_SIGN_IDENTITY="$FRAME_CODESIGN_IDENTITY_DEFAULT"
build_version="0.0.0-SNAPSHOT"
generate_xcodeproj=1
generate_git_hash=0
while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2 ;;
        --codesign-identity) XCODEGEN_FRAME_CODE_SIGN_IDENTITY="$2"; shift 2 ;;
        --generate-git-hash) generate_git_hash=1; shift 1;;
        --ignore-xcodeproj) generate_xcodeproj=0; shift 1 ;;
        *) echo "Unknown option $1"; exit 1 ;;
    esac
done

cat > Sources/Common/versionGenerated.swift <<EOF
// FILE IS GENERATED BY generate.sh
public let appVersion = "$build_version"
EOF

cat <<EOF > ./Sources/Common/gitHashGenerated.swift
// FILE IS GENERATED BY generate.sh
public let gitHash = "$(if test $generate_git_hash = 0; then echo "SNAPSHOT"; else git rev-parse HEAD; fi)"
public let gitShortHash = "$(if test $generate_git_hash = 0; then echo "SNAPSHOT"; else git rev-parse --short HEAD; fi)"
EOF

if test $generate_xcodeproj = 1; then
    export XCODEGEN_FRAME_VERSION=$build_version
    ./script/install-dep.sh --xcodegen
    ./.deps/xcodegen/xcodegen # https://github.com/yonaskolb/XcodeGen
fi
